///Shuriken fill weapon mpa
///@arg potion
///@arg weapon-map
function scPotionStart(argument0, argument1) {

	scPotionChange(argument0, argument1);

	enum WEAPON_POTION_TYPE {
		NONE, DEFAULT, ICE, FIRE, PORTAL, BRICK, MAGNET ,SLIME, SAND, SHOTGUN, METAL, ELECTRIC
	}

	enum POTION_SPRITE {
		NONE = noone, DEFAULT = sPotion_Default,ICE = sPotion_Ice, FIRE = sPotion_Fire, PORTAL = sPotion_Portal, 
		BRICK = sPotion_Brick,  MAGNET = sPotion_Default, SAND = sPotion_Default, SHOTGUN = sPotion_Shotgun,
		SLIME = sPotion_Slime, METAL = sPotion_Spike, ELECTRIC = sPotion_Electric, 
	}

	enum POTION_MAP {

		//BASIC VARIABLES
		SPEED, DAMAGE, STICK, RELOAD_TIME, NAME, DESCRIPTION, TIMER, TYPE, PROJECTILE,
		COOLDOWN,CLIP,STARTUP, SCALE, POTION_STEP,BUFF,KBAMT, DELETE_ON_HIT, HIT_SCRIPT,
		POTION_AUTO_DESTROY, POTION_AUTO_DESTROY_ROOM, PARTICLE, PARTICLE_SPLASH, PARTICLE_SPLASH_COLOR, PARTICLE_AMT, WALL_COLLIDE, WEIGHT,
		DESPAWN_SCRIPT, WALL_SCRIPT, PLAYER_SCRIPT,WEAPON_SCRIPT, ROTATE, SPAWN_SCRIPT, SPRITE_STICK,
		//ULTIMATE
		/*ULTIMATE,*/ 
		ULTIMATE_CHARGE_GIVE, ULTIMATE_CHARGE_MULTIPLIER,
		//UNIQUE
		DEATHCAUSE,

	}


}
