owner = noone;
first_step = false;
exit_x = 0;
exit_y = 0;
exit_created = false;
teleported = ds_list_create();
timer_org = 3 * room_speed;
timer = timer_org; //placement time
portal_timer = 10 * room_speed; //portal uptime
portal_alpha = 0;
image_alpha = 0;
max_alpha = 1;
alpha_change = 0.02;