
scShurikenChange(argument0);

enum SHURIKEN {
	NONE,DEFAULT,ICE,
}

enum SHURIKEN_SPRITE{
	NONE = noone, DEFAULT = sShuriken_Default,ICE = sShuriken_Ice,
}

enum SHURIKEN_MAP{

	//BASIC VARIABLES
	SPEED,DAMAGE,STICK,RELOAD_TIME, NAME, DESCRIPTION, TIMER, TYPE,PROJECTILE,
	COOLDOWN,CLIP,STARTUP, SCALE, SHURIKEN_STEP,BUFF,KBAMT,
	SHURIKEN_AUTO_DESTROY,SHURIKEN_AUTO_DESTROY_ROOM, PARTICLE,PARTICLE_AMT,
	//ULTIMATE
	ULTIMATE,ULTIMATE_CHARGE_GIVE,ULTIMATE_CHARGE_MULTIPLIER,
	
	//UNIQUE
	DEATHCAUSE,

}