
scShurikenChange(argument0);

enum SHURIKEN {
	NONE,DEFAULT,	
}

enum SHURIKEN_SPRITE{
	NONE = noone, DEFAULT = sShuriken_Default,	
}

enum SHURIKEN_MAP{

	//BASIC VARIABLES
	SPEED,DAMAGE,STICK,RELOAD_TIME, NAME, DESCRIPTION, TIMER, TYPE,PROJECTILE,
	COOLDOWN,CLIP,STARTUP, SCALE, SHURIKEN_STEP,BUFF,KBAMT,
	SHURIKEN_AUTO_DESTROY,SHURIKEN_AUTO_DESTROY_ROOM,
	//ULTIMATE
	ULTIMATE,ULTIMATE_CHARGE_GIVE,ULTIMATE_CHARGE_MULTIPLIER,
	
	//UNIQUE
	DEATHCAUSE,

}