///@desc get a characters info (Delete after grabbing)
///@arg character
function scPlayerCharacterGetInfo(argument0) {

	var map = ds_map_create();
	map[? CHARACTER_MAP.TYPE] = argument0;
	//map[? CHARACTER_MAP.WEAPON] = WEAPON.ROCKET; //Default weapon
	map[? CHARACTER_MAP.HEALTH_BASE] = 0; //Default health
	map[? CHARACTER_MAP.HEALTH_ARMOR] = 0; //Default armor
	map[? CHARACTER_MAP.HEALTH_SHIELD] = 0; //Default shield
	map[? CHARACTER_MAP.HEALTH_VITAL] = 0;
	map[? CHARACTER_MAP.NAME] = "Bob"; //Default name
	map[? CHARACTER_MAP.PALETTE] = noone;
	map[? CHARACTER_MAP.PALETTE_INDEX] = 5;
	map[? CHARACTER_MAP.CAN_PICK] = true;
	map[? CHARACTER_MAP.ULTIMATE] = noone;
	map[? CHARACTER_MAP.ABILITY] = ABILITY_TYPE.NONE;
	map[? CHARACTER_MAP.WEAPON] = WEAPON_TYPE.NONE;
	map[? CHARACTER_MAP.SPEED] = 8; //Default speed

	switch (map[? CHARACTER_MAP.TYPE]) {
		case CHARACTER.DEFAULT:
			map[? CHARACTER_MAP.NAME] = "Steve";
			map[? CHARACTER_MAP.WEAPON] = WEAPON_TYPE.ROCKET;
			map[? CHARACTER_MAP.HEALTH_BASE] = 20;
			map[? CHARACTER_MAP.HEALTH_ARMOR] = 20;
			map[? CHARACTER_MAP.HEALTH_VITAL] = 20;
			map[? CHARACTER_MAP.PALETTE] = sPallete_default;
			map[? CHARACTER_MAP.ULTIMATE] = ULTIMATE_TYPE.HOMING;
			map[? CHARACTER_MAP.ABILITY] = ABILITY_TYPE.BIGROCKET;
			break;
		case CHARACTER.SWORD:
			map[? CHARACTER_MAP.NAME] = "Zato";
			map[? CHARACTER_MAP.WEAPON] = WEAPON_TYPE.SHURIKEN;
			map[? CHARACTER_MAP.HEALTH_BASE] = 30;
			map[? CHARACTER_MAP.PALETTE] = sPallete_sword;
			map[? CHARACTER_MAP.ULTIMATE] = ULTIMATE_TYPE.JUMPPAD;
			map[? CHARACTER_MAP.ABILITY] = ABILITY_TYPE.REFLECT;
			break;
		case CHARACTER.ARROW:
			map[? CHARACTER_MAP.NAME] = "Hush";
			map[? CHARACTER_MAP.WEAPON] = WEAPON_TYPE.ARROW;
			map[? CHARACTER_MAP.HEALTH_BASE] = 70;
			map[? CHARACTER_MAP.HEALTH_ARMOR] = 0;
			map[? CHARACTER_MAP.HEALTH_SHIELD] = 30;
			map[? CHARACTER_MAP.PALETTE] = sPallete_arrow;
			map[? CHARACTER_MAP.ULTIMATE] = ULTIMATE_TYPE.TRAP;
			map[? CHARACTER_MAP.ABILITY] = ABILITY_TYPE.PORTAL;
			break;
			
		case CHARACTER.POTION:
			map[? CHARACTER_MAP.NAME] = "Tonic";
			map[? CHARACTER_MAP.WEAPON] = WEAPON_TYPE.POTION;
			map[? CHARACTER_MAP.HEALTH_BASE] = 64;
			map[? CHARACTER_MAP.HEALTH_ARMOR] = 13;
			map[? CHARACTER_MAP.HEALTH_SHIELD] = 23;
			map[? CHARACTER_MAP.PALETTE] = sPallete_potion;
			map[? CHARACTER_MAP.ULTIMATE] = ULTIMATE_TYPE.AMPWALL;
			map[? CHARACTER_MAP.ABILITY] = ABILITY_TYPE.JUMPPAD;
			break;		
			
		case CHARACTER.BOMB:
			map[? CHARACTER_MAP.NAME] = "Clyde";
			map[? CHARACTER_MAP.WEAPON] = WEAPON_TYPE.BOMB;
			map[? CHARACTER_MAP.HEALTH_BASE] = 25;
			map[? CHARACTER_MAP.HEALTH_ARMOR] = 15;
			map[? CHARACTER_MAP.HEALTH_VITAL] = 10;
			map[? CHARACTER_MAP.PALETTE] = sPalette_bomb;
			map[? CHARACTER_MAP.ULTIMATE] = ULTIMATE_TYPE.VORTEX;
			map[? CHARACTER_MAP.ABILITY] = ABILITY_TYPE.CLUSTER;
			break;	
		
		case CHARACTER.GUN:
			map[? CHARACTER_MAP.NAME] = "Dell";
			map[? CHARACTER_MAP.WEAPON] = WEAPON_TYPE.BULLET;
			map[? CHARACTER_MAP.HEALTH_BASE] = 75;
			map[? CHARACTER_MAP.HEALTH_VITAL] = 25;
			map[? CHARACTER_MAP.PALETTE] = sPalette_gun;
			map[? CHARACTER_MAP.ULTIMATE] = ULTIMATE_TYPE.PORTAL;
			map[? CHARACTER_MAP.ABILITY] = ABILITY_TYPE.DODGE;
			break;	
		
	}

	return map;


}
