///Shuriken fill weapon mpa
///@arg bomb
///@arg weapon-map
function scBombStart(argument0, argument1) {

	scBombChange(argument0, argument1);

	enum WEAPON_BOMB_TYPE {
		NONE, DEFAULT, ICE, FIRE, PORTAL, BRICK, MAGNET ,SLIME, SAND, SHOTGUN, METAL, ELECTRIC
	}

	enum BOMB_SPRITE {
		NONE = noone, DEFAULT = sBomb_Default,ICE = sBomb_Default, FIRE = sBomb_Default, PORTAL = sBomb_Default, 
		BRICK = sBomb_Default,  MAGNET = sBomb_Default, SAND = sBomb_Default, SHOTGUN = sBomb_Default,
		SLIME = sBomb_Default, METAL = sBomb_Default, ELECTRIC = sBomb_Default, 
	}

	enum BOMB_MAP {

		//BASIC VARIABLES
		SPEED, DAMAGE, STICK, RELOAD_TIME, NAME, DESCRIPTION, TIMER, TYPE, PROJECTILE,
		COOLDOWN,CLIP,STARTUP, SCALE, BOMB_STEP,BUFF,KBAMT, DELETE_ON_HIT, HIT_SCRIPT,
		BOMB_AUTO_DESTROY, BOMB_AUTO_DESTROY_ROOM, PARTICLE, PARTICLE_SPLASH, PARTICLE_SPLASH_COLOR, PARTICLE_AMT, WALL_COLLIDE, WEIGHT,
		DESPAWN_SCRIPT, WALL_SCRIPT, PLAYER_SCRIPT,WEAPON_SCRIPT, ROTATE, SPAWN_SCRIPT, SPRITE_STICK,
		PARTICLE_EXPLOSION, SHAKE_MAGNITUDE, SHAKE_FRAMES, EXPLOSION_CREATE, EXPLOSION_CREATE_DRAW,
		EXPLOSION_SCALE, EXPLOSION_SPRITE, EXPLOSION_STEP,
		//ULTIMATE
		/*ULTIMATE,*/ 
		ULTIMATE_CHARGE_GIVE, ULTIMATE_CHARGE_MULTIPLIER,
		//UNIQUE
		DEATHCAUSE,

	}


}
