/// @arg rocket
/// @arg weapon-map
function scRocketStart(argument0, argument1) {

	scRocketChange(argument0, argument1);

	enum WEAPON_ROCKET_TYPE {
		NONE, DEFAULT, FAST, HOMING, REVERSE, ICE, FIRE, SAND, LASER, SLIME,
		RANDOM, BOUNCY, SPIKED, MAGNET, OBSOLETE, LIGHTNING, SHOTGUN, PEACE,
		TELEPORT, ARCHING, BOOMERANG, BRICK, PIERCING, GLASS, 
		//KEEP LAST
		LENGHT
	}

	enum ROCKET_SPRITE {
		//Mostly used to save memory on oRocketPickup, or to insta grab a rocket sprite
		NONE = noone, DEFAULT = sRocket_Default, FAST = sRocket_Fast, HOMING = sRocket_Homing, REVERSE = sRocket_Reverse, 
		ICE = sRocket_Ice, FIRE = sRocket_Fire, SAND = sRocket_Sand, LASER = sRocket_Laser, SLIME = sRocket_Slime,
		RANDOM = sRocket_Random, BOUNCY = sRocket_Bouncy, SPIKED = sRocket_Spiked, MAGNET = sRocket_Magnet, OBSOLETE = sRocket_Obsolete,
		LIGHTNING = sRocket_Lightning, SHOTGUN = sRocket_Shotgun, PEACE = sRocket_Peace, TELEPORT = sRocket_Teleport,
		ARCHING = sRocket_Arching, BOOMERANG = sRocket_Boomerang, BRICK = sRocket_Brick, PIERCING = sRocket_Piercing,
		GLASS = sRocket_Glass,
	}

	enum ROCKET_MAP {
		//BASIC VARIABLES
		RECOIL, PROJECTILE, COOLDOWN, SPEED, OFFSET, STARTUP, CLIP, RELOAD_TIME,
		TIMER, IGNORE_WALL, NAME, DESCRIPTION, BUFF, TYPE, ENABLED, SCALE, KBAMT,
		ROCKET_AUTO_DESTROY, ROCKET_AUTO_DESTROY_ROOM, HIT_PICKUP,
		//DAMAGE TYPES
		DAMAGE, DAMAGE_ROCKET, DAMAGE_EXPLOSION,
		//ROCKET EVENTS
		ROCKET_CREATE, ROCKET_STEP, ROCKET_DRAW_OVER, ROCKET_DRAW_UNDER, ROCKET_DRAW_EXTRA, ROCKET_DESTROY, ROCKET_ALPHA,
		//PARTICLES
		PARTICLE_TRAIL, PARTICLE_EXPLOSION, PARTICLE_AMT, PARTICLE_CHANGE_ORIENTATION,
		//CAMERA SHAKE
		SHAKE_MAGNITUDE, SHAKE_FRAMES,
		//EXPLOSION SCRIPTS
		EXPLOSION_SPRITE, EXPLOSION_ROCKET, EXPLOSION_WALL, EXPLOSION_SHOOTABLE, EXPLOSION_STEP, EXPLOSION_CREATE,
		EXPLOSION_CREATE_DRAW, EXPLOSION_SCALE,
		//SOUND EFFECTS
		SOUND_EXPLOSION, SOUND_SHOOT,
		//ULTIMATE
		/*ULTIMATE,*/ ULTIMATE_CHARGE_GIVE, ULTIMATE_CHARGE_MULTIPLIER,
		//UNIQUE
		UNIQUE_CANBOUNCE, DEATHCAUSE, GO_OOB,
	}


}
