hugeMap = ds_map_create();
var map = hugeMap;
size = 1.3;
map[? "sprite"] = sprite_index;
map[? "spd"] = rocket_map[? ROCKET_MAP.SPEED] * 2;
sprite_index = sNuke_Default;
map[? "dis"] = (RES_W / 2) - rocket_map[? ROCKET_MAP.OFFSET];
map[? "dis_crt"] = 0;
map[? "amt"] = 8;